-- Create table 北京市
create table T_TERM_RESOURCE_RELATION_11
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);
-- Add comments to the columns 
comment on column T_TERM_RESOURCE_RELATION_11.RESOURCE_ID
  is '资源id';
comment on column T_TERM_RESOURCE_RELATION_11.RESOURCE_NAME
  is '资源名称';
comment on column T_TERM_RESOURCE_RELATION_11.TERM_ID
  is '终端id';
comment on column T_TERM_RESOURCE_RELATION_11.TERM_NAME
  is '终端名称';
comment on column T_TERM_RESOURCE_RELATION_11.SUBJECT_ID
  is '学科id';
comment on column T_TERM_RESOURCE_RELATION_11.CLASS_ID
  is '年级id';
comment on column T_TERM_RESOURCE_RELATION_11.OPT_TYPE
  is '操作类型，已接收、下载、点击';
comment on column T_TERM_RESOURCE_RELATION_11.REGOIN_ID
  is '区划id';
comment on column T_TERM_RESOURCE_RELATION_11.REGOIN_NAME
  is '区划名称';
comment on column T_TERM_RESOURCE_RELATION_11.OPT_TIME
  is '操作时间';

--天津市
create table T_TERM_RESOURCE_RELATION_12
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);


--河北省
create table T_TERM_RESOURCE_RELATION_13
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--山西省
create table T_TERM_RESOURCE_RELATION_14
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--内蒙古自治区
create table T_TERM_RESOURCE_RELATION_15
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--辽宁省
create table T_TERM_RESOURCE_RELATION_21
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--吉林省
create table T_TERM_RESOURCE_RELATION_22
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--黑龙江省
create table T_TERM_RESOURCE_RELATION_23
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--上海市
create table T_TERM_RESOURCE_RELATION_31
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--江苏省
create table T_TERM_RESOURCE_RELATION_32
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--浙江省
create table T_TERM_RESOURCE_RELATION_33
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--安徽省
create table T_TERM_RESOURCE_RELATION_34
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--福建省
create table T_TERM_RESOURCE_RELATION_35
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--江西省
create table T_TERM_RESOURCE_RELATION_36
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--山东省
create table T_TERM_RESOURCE_RELATION_37
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--河南省
create table T_TERM_RESOURCE_RELATION_41
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--湖北省
create table T_TERM_RESOURCE_RELATION_42
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--湖南省
create table T_TERM_RESOURCE_RELATION_43
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--广东省
create table T_TERM_RESOURCE_RELATION_44
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--广西壮族自治区
create table T_TERM_RESOURCE_RELATION_45
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--海南省
create table T_TERM_RESOURCE_RELATION_46
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--重庆市
create table T_TERM_RESOURCE_RELATION_50
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--四川省
create table T_TERM_RESOURCE_RELATION_51
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--贵州省
create table T_TERM_RESOURCE_RELATION_52
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--云南省
create table T_TERM_RESOURCE_RELATION_53
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--云南省
create table T_TERM_RESOURCE_RELATION_54
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--陕西省
create table T_TERM_RESOURCE_RELATION_61
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--甘肃省
create table T_TERM_RESOURCE_RELATION_62
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--青海省
create table T_TERM_RESOURCE_RELATION_63
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--宁夏回族自治区
create table T_TERM_RESOURCE_RELATION_64
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--新疆维吾尔自治区
create table T_TERM_RESOURCE_RELATION_65
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);

--新疆生产建设兵团
create table T_TERM_RESOURCE_RELATION_66
(
  RESOURCE_ID   VARCHAR2(42),
  RESOURCE_NAME VARCHAR2(80),
  TERM_ID       VARCHAR2(42),
  TERM_NAME     VARCHAR2(80),
  SUBJECT_ID    VARCHAR2(42),
  CLASS_ID      VARCHAR2(42),
  OPT_TYPE      VARCHAR2(8),
  REGOIN_ID     VARCHAR2(42),
  REGOIN_NAME   VARCHAR2(80),
  OPT_TIME      DATE
);