package com.analysis.xfire.service;

// Generated by MyEclipse

public interface ITermService{

	/**
	 * 
	 * @功能：已接收
	 * 
	 * @param json
	 * @return
	 */
	public String takeOver(String json);

	/**
	 * 
	 * @功能：未开机
	 * 
	 * @param json
	 * @return
	 */
	public String unBootStrap(String json);

	/**
	 * 
	 * @功能：点击量
	 * 
	 * @param json
	 * @return
	 */
	public String clickedCount(String json);

	/**
	 * 
	 * @功能：下载量
	 * 
	 * @param json
	 * @return
	 */
	public String downloadCount(String json);

}
