package com.analysis.xfire.service;

import java.util.List;

import com.analysis.dao.TermResourceDaoImpl;
import com.analysis.po.TermResourceRelation;
import com.analysis.po.TermUnBootStrap;
import com.analysis.utils.Constant;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;

// Generated by MyEclipse

public class TermServiceImpl implements ITermService{

	/**
	 * 已接收
	 */
	public String takeOver(String json){
		List<TermResourceRelation> list = this.fromJson2Object(json);
		this.save(list, Constant.TAKE_OVER_TYPE);
		return "1";
	}

	/**
	 * 未开机
	 */
	public String unBootStrap(String json){
		Gson g = new GsonBuilder().setDateFormat("yyyy-MM-dd HH:mm:ss")
				.create();
		List<TermUnBootStrap> list = g.fromJson(json,
				new TypeToken<List<TermUnBootStrap>>(){
				}.getType());

		TermResourceDaoImpl daoImpl = new TermResourceDaoImpl();
		for(TermUnBootStrap strap : list){
			daoImpl.saveUnBootStrap(strap);
		}
		return "1";
	}

	/**
	 * 点击量
	 */
	public String clickedCount(String json){
		List<TermResourceRelation> list = this.fromJson2Object(json);
		this.save(list, Constant.CLICKED_COUNT_TYPE);
		return "1";
	}

	/**
	 * 下载量
	 */
	public String downloadCount(String json){
		List<TermResourceRelation> list = this.fromJson2Object(json);
		this.save(list, Constant.DOWNLOAD_COUNT_TYPE);
		return "1";
	}

	private void save(List<TermResourceRelation> list, String optType){
		TermResourceDaoImpl daoImpl = new TermResourceDaoImpl();
		for(TermResourceRelation relation : list){
			String code = daoImpl.getProvinceCode(relation.getTermId());
			daoImpl.saveAll(relation, optType, code);
		}
	}

	private List<TermResourceRelation> fromJson2Object(String json){
		Gson g = new GsonBuilder().setDateFormat("yyyy-MM-dd HH:mm:ss")
				.create();
		List<TermResourceRelation> list = g.fromJson(json,
				new TypeToken<List<TermResourceRelation>>(){
				}.getType());
		return list;
	}
}
